#!/bin/sh
# Check the channel's packages for newer upstream releases and print a
# Markdown report grouped by build-set.  Driven by `guix refresh`, which
# tracks crates.io and git-tag sources automatically; packages whose
# source has no usable updater (custom download URLs) are listed for a
# manual look with a link to upstream.
#
# Used by the monthly .github/workflows/refresh.yml to open a tracking
# issue.  Run it locally the same way: `etc/ci-refresh-report.sh`.
#
# Exit status: 0 always.  Whether any upgrade was found is written to
# $GITHUB_OUTPUT as `updates=true|false` when running under Actions.
set -eu

# (etc ci-packages) transitively imports bitcoin/packages/wallets.scm, whose
# sparrow-wallet needs (nonguix build-system binary); add the nonguix checkout
# (created by ci-setup-guix.sh) to the load path when present.
NONGUIX_DIR="${NONGUIX_DIR:-/tmp/guix-nonguix}"
nonguix_L=""
[ -d "$NONGUIX_DIR" ] && nonguix_L="-L $NONGUIX_DIR"

# set name : ci-packages.scm variable
SETS="libs:%libs-packages nodes:%node-packages wallets:%wallet-packages indexers:%indexer-packages lightning:%lightning-packages rust:%rust-packages explorers:%explorer-packages binary:%binary-packages"

# GitHub repo whose Releases page tracks a package whose source URL guix
# refresh cannot follow.  We query the releases API directly for these.
release_repo() {
    case "$1" in
        bitcoin-core)  echo "bitcoin/bitcoin" ;;
        bitcoin-knots) echo "bitcoinknots/bitcoin" ;;
        mempool-backend|mempool-frontend|mempool-rust-gbt)
                       echo "mempool/mempool" ;;
        sparrow-wallet) echo "sparrowwallet/sparrow" ;;
        *)             echo "" ;;
    esac
}

# Latest published (non-prerelease) release version for a GitHub repo, with
# any leading "v" stripped.  Empty on any failure (rate limit, network).
github_latest() {
    json=$(wget -qO- --timeout=20 \
               --header='Accept: application/vnd.github+json' \
               "https://api.github.com/repos/$1/releases/latest" 2>/dev/null) \
        || return 0
    tag=$(printf '%s' "$json" \
              | grep -oE '"tag_name"[[:space:]]*:[[:space:]]*"[^"]+"' \
              | head -1 | grep -oE '"[^"]+"$' | tr -d '"')
    printf '%s' "${tag#v}"
}

# Print "name version" for each package in a ci-packages.scm list variable.
# Script mode (guix repl -- FILE) prints no REPL banner, unlike a heredoc.
names_versions() {
    _nv_script=$(mktemp)
    cat > "$_nv_script" <<EOF
(use-modules (etc ci-packages) (guix packages))
(for-each (lambda (p) (format #t "~a ~a~%" (package-name p) (package-version p)))
          $1)
EOF
    guix repl -L . $nonguix_L -- "$_nv_script" 2>/dev/null
    rm -f "$_nv_script"
}

found_updates=false

{
    printf '# Monthly package update check\n\n'
    printf 'Generated by `etc/ci-refresh-report.sh` (via `guix refresh`). '
    printf 'Bumps need a signed commit and, for vendored packages, manual hash '
    printf 'harvesting (lnd vendor, npm caches, rust-gbt) — see CONTRIBUTING.md.\n\n'
    printf 'Legend: ⬆️ update available · 🔍 no auto-updater, check upstream · ✅ current\n'
} > /tmp/refresh-report.md

for entry in $SETS; do
    set_name=${entry%%:*}
    var=${entry#*:}

    nv=$(names_versions "$var")
    names=$(printf '%s\n' "$nv" | awk '{print $1}')

    # One refresh pass for the whole set; categorize each package below.
    out=$(guix refresh -L . $nonguix_L $names 2>&1 || true)

    printf '## %s\n\n' "$set_name" >> /tmp/refresh-report.md
    printf '%s\n' "$nv" | while read -r name version; do
        [ -n "$name" ] || continue

        # Packages tracked via the GitHub Releases API (custom download URLs
        # guix refresh cannot follow, e.g. bitcoin-core, bitcoin-knots).
        repo=$(release_repo "$name")
        if [ -n "$repo" ]; then
            latest=$(github_latest "$repo")
            if [ -n "$latest" ]; then
                if [ "$latest" = "$version" ]; then
                    printf -- '- ✅ %s %s\n' "$name" "$version"
                else
                    newest=$(printf '%s\n%s\n' "$version" "$latest" | sort -V | tail -1)
                    if [ "$newest" = "$latest" ]; then
                        printf -- '- ⬆️ **%s** %s → %s available <https://github.com/%s/releases>\n' \
                               "$name" "$version" "$latest" "$repo"
                    else
                        printf -- '- ✅ %s %s (ahead of upstream %s)\n' \
                               "$name" "$version" "$latest"
                    fi
                fi
                continue
            fi
            # API unreachable: fall back to a manual-check line with the link.
            printf -- '- 🔍 **%s** %s — release check failed; see <https://github.com/%s/releases>\n' \
                   "$name" "$version" "$repo"
            continue
        fi

        up=$(printf '%s\n' "$out" | grep -E "$name would be upgraded from" | head -1 || true)
        if [ -n "$up" ]; then
            detail=$(printf '%s\n' "$up" | sed 's/.*would be upgraded/available:/')
            printf -- '- ⬆️ **%s** %s\n' "$name" "$detail"
        elif printf '%s\n' "$out" | grep -qE "latest version of $name\$"; then
            printf -- '- ✅ %s %s\n' "$name" "$version"
        else
            printf -- '- 🔍 **%s** %s — updater could not determine latest\n' \
                   "$name" "$version"
        fi
    done >> /tmp/refresh-report.md
    printf '\n' >> /tmp/refresh-report.md
done

# Any ⬆️ list item (from guix refresh or the GitHub release check) means
# action -- anchored to "- ⬆️" so the legend line does not count.
if grep -qE '^- ⬆️' /tmp/refresh-report.md; then
    found_updates=true
fi

{
    printf -- '---\n'
    if [ "$found_updates" = true ]; then
        printf 'At least one package has an upstream update available (⬆️ above).\n'
    else
        printf 'No automatic updates detected this month. The 🔍 packages have no '
        printf 'updater, so check their upstreams by hand — a new release will not '
        printf 'show up here.\n'
    fi
} >> /tmp/refresh-report.md

cat /tmp/refresh-report.md

# Surface the result for the workflow (whether to flag the issue).
if [ -n "${GITHUB_OUTPUT:-}" ]; then
    echo "updates=$found_updates" >> "$GITHUB_OUTPUT"
fi
