#!/bin/sh
# Check the channel's packages for newer upstream releases and print a
# Markdown report grouped by build-set.  Driven by `guix refresh`, which
# tracks crates.io and git-tag sources automatically; packages whose
# source has no usable updater (custom download URLs) are listed for a
# manual look with a link to upstream.
#
# Used by the monthly .github/workflows/refresh.yml to open a tracking
# issue.  Run it locally the same way: `etc/ci-refresh-report.sh`.
#
# Exit status: 0 always.  Whether any upgrade was found is written to
# $GITHUB_OUTPUT as `updates=true|false` when running under Actions.
set -eu

# set name : ci-packages.scm variable
SETS="light:%light-packages nodes:%node-packages wallets:%wallet-packages indexers:%indexer-packages lightning:%lightning-packages rust:%rust-packages explorers:%explorer-packages"

# Upstream release pages for packages guix refresh cannot track.
manual_url() {
    case "$1" in
        bitcoin-core)  echo "https://bitcoincore.org/en/download/" ;;
        bitcoin-knots) echo "https://bitcoinknots.org/" ;;
        univalue)      echo "https://github.com/jgarzik/univalue/tags" ;;
        mempool-backend|mempool-frontend|mempool-rust-gbt)
                       echo "https://github.com/mempool/mempool/releases" ;;
        *)             echo "" ;;
    esac
}

# Print "name version" for each package in a ci-packages.scm list variable.
# Script mode (guix repl -- FILE) prints no REPL banner, unlike a heredoc.
names_versions() {
    _nv_script=$(mktemp)
    cat > "$_nv_script" <<EOF
(use-modules (etc ci-packages) (guix packages))
(for-each (lambda (p) (format #t "~a ~a~%" (package-name p) (package-version p)))
          $1)
EOF
    guix repl -L . -- "$_nv_script" 2>/dev/null
    rm -f "$_nv_script"
}

found_updates=false

{
    printf '# Monthly package update check\n\n'
    printf 'Generated by `etc/ci-refresh-report.sh` (via `guix refresh`). '
    printf 'Bumps need a signed commit and, for vendored packages, manual hash '
    printf 'harvesting (lnd vendor, npm caches, rust-gbt) — see CONTRIBUTING.md.\n\n'
    printf 'Legend: ⬆️ update available · 🔍 no auto-updater, check upstream · ✅ current\n'
} > /tmp/refresh-report.md

for entry in $SETS; do
    set_name=${entry%%:*}
    var=${entry#*:}

    nv=$(names_versions "$var")
    names=$(printf '%s\n' "$nv" | awk '{print $1}')

    # One refresh pass for the whole set; categorize each package below.
    out=$(guix refresh -L . $names 2>&1 || true)

    printf '## %s\n\n' "$set_name" >> /tmp/refresh-report.md
    printf '%s\n' "$nv" | while read -r name version; do
        [ -n "$name" ] || continue
        up=$(printf '%s\n' "$out" | grep -E "$name would be upgraded from" | head -1 || true)
        if [ -n "$up" ]; then
            detail=$(printf '%s\n' "$up" | sed 's/.*would be upgraded/available:/')
            printf -- '- ⬆️ **%s** %s\n' "$name" "$detail"
        elif printf '%s\n' "$out" | grep -qE "latest version of $name\$"; then
            printf -- '- ✅ %s %s\n' "$name" "$version"
        else
            url=$(manual_url "$name")
            if [ -n "$url" ]; then
                printf -- '- 🔍 **%s** %s — no auto-updater; check <%s>\n' \
                       "$name" "$version" "$url"
            else
                printf -- '- 🔍 **%s** %s — updater could not determine latest\n' \
                       "$name" "$version"
            fi
        fi
    done >> /tmp/refresh-report.md
    printf '\n' >> /tmp/refresh-report.md

    if printf '%s\n' "$out" | grep -qE 'would be upgraded from'; then
        found_updates=true
    fi
done

{
    printf -- '---\n'
    if [ "$found_updates" = true ]; then
        printf 'At least one package has an upstream update available (⬆️ above).\n'
    else
        printf 'No automatic updates detected this month. The 🔍 packages have no '
        printf 'updater, so check their upstreams by hand — a new release will not '
        printf 'show up here.\n'
    fi
} >> /tmp/refresh-report.md

cat /tmp/refresh-report.md

# Surface the result for the workflow (whether to flag the issue).
if [ -n "${GITHUB_OUTPUT:-}" ]; then
    echo "updates=$found_updates" >> "$GITHUB_OUTPUT"
fi
