;;; Copyright © 2026 Trevor Arjeski <tmarjeski@gmail.com>
;;;
;;; This file is part of guix-bitcoin.
;;;
;;; guix-bitcoin is free software; you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by the
;;; Free Software Foundation; either version 3 of the License, or (at your
;;; option) any later version.
;;;
;;; guix-bitcoin --- channel-local Rust crate sources.
;;; This file is partially machine-generated by 'guix import crate
;;; --lockfile'.  Regenerate per-app entries on version bumps.
;;;
;;; Regeneration:
;;;
;;;   * For an application (e.g. electrs), run against the app's own
;;;     lockfile:
;;;
;;;       guix import crate --lockfile=<checkout>/Cargo.lock <app>
;;;
;;;     then update that app's `define-cargo-inputs' row with the emitted
;;;     crate list.
;;;
;;;   * For the standalone library crates (those not owned by an app row),
;;;     generate a lockfile workspace per library by running
;;;     `cargo generate-lockfile' against an exact-pinned dependency on the
;;;     library, then re-import from that lockfile as above.
;;;
;;; After importing: dedupe crate+version across rows (a given
;;; crate-source must be defined once), keep the crate-source defs sorted
;;; alphabetically, and keep each app's define-cargo-inputs row sorted.
(define-module (btc packages rust-crates)
  #:use-module (guix build-system cargo)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:export (lookup-cargo-inputs))

(define rust-ahash-0.8.12
  (crate-source "ahash" "0.8.12"
                "0xbsp9rlm5ki017c0w6ay8kjwinwm8knjncci95mii30rmwz25as"))

(define rust-aho-corasick-1.1.3
  (crate-source "aho-corasick" "1.1.3"
                "05mrpkvdgp5d20y2p989f187ry9diliijgwrs254fs9s1m1x6q4f"))

(define rust-anyhow-1.0.98
  (crate-source "anyhow" "1.0.98"
                "11ylvjdrcjs0q9jgk1af4r5cx1qppj63plxqkq595vmc24rjsvg1"))

(define rust-arrayvec-0.7.6
  (crate-source "arrayvec" "0.7.6"
                "0l1fz4ccgv6pm609rif37sl5nv5k6lbzi7kkppgzqzh1vwix20kw"))

(define rust-ascii-1.1.0
  (crate-source "ascii" "1.1.0"
                "05nyyp39x4wzc1959kv7ckwqpkdzjd9dw4slzyjh73qbhjcfqayr"))

(define rust-autocfg-1.4.0
  (crate-source "autocfg" "1.4.0"
                "09lz3by90d2hphbq56znag9v87gfpd9gb8nr82hll8z6x2nhprdc"))

(define rust-base58ck-0.1.0
  (crate-source "base58ck" "0.1.0"
                "0pv0k3d1q3lnqisqrb3padx0cmh2rrr4ag4iq62s8bisb946d39c"))

(define rust-base58ck-0.1.100
  (crate-source "base58ck" "0.1.100"
                "05kqhicnb33xpk5zrx0a9v4a4wbbdl406z6sc805zcbvkzhcfpgc"))

(define rust-base64-0.13.1
  (crate-source "base64" "0.13.1"
                "1s494mqmzjb766fy1kqlccgfg2sdcjb6hzbvzqv2jw65fdi5h6wy"))

(define rust-base64-0.21.7
  (crate-source "base64" "0.21.7"
                "0rw52yvsk75kar9wgqfwgb414kvil1gn7mqkrhn9zf1537mpsacx"))

(define rust-bdk-chain-0.23.3
  (crate-source "bdk_chain" "0.23.3"
                "1h2650nk8wf7car24vws56m6nifam5h62ax8qp08m6kr73qfz462"))

(define rust-bdk-core-0.6.3
  (crate-source "bdk_core" "0.6.3"
                "0fjs4y1gsbgcg543x9a0b8mjfssfscrl6947z5nlmwbb5xw2hc6b"))

(define rust-bech32-0.11.0
  (crate-source "bech32" "0.11.0"
                "07cmbj8ynqpj01wzj4pgj27i2c6n66gf8zma8k6xxdz3jrhl8rfr"))

(define rust-bech32-0.11.1
  (crate-source "bech32" "0.11.1"
                "0zwfapdphq2fnd1f75hs6zfya75sgwzdwlbdih5b3ivz6xl74qrj"))

(define rust-bindgen-0.69.5
  (crate-source "bindgen" "0.69.5"
                "1240snlcfj663k04bjsg629g4wx6f83flgbjh5rzpgyagk3864r7"))

(define rust-bitcoin-0.32.100
  (crate-source "bitcoin" "0.32.100"
                "0v0vx5srvby18nqih2b28786yx3jygfpbfk869gjh48i4jci4n1r"))

(define rust-bitcoin-0.32.8
  (crate-source "bitcoin" "0.32.8"
                "0rhg1kmqb17ci4b2wxxnfsgl0zd69ys4lx5gk3z50zs0q2gryj8y"))

(define rust-bitcoin-consensus-encoding-1.0.0
  (crate-source "bitcoin-consensus-encoding" "1.0.0"
                "0h5a05608fk9kzlcv1b7w33c640s1nhyavsrb8xwk8qv5970kmmj"))

(define rust-bitcoin-hashes-0.14.0
  (crate-source "bitcoin_hashes" "0.14.0"
                "05jdirz6p2q1fbg65c1xfhf8bsx7snpzm9i1g8a7w95h1lyw065v"))

(define rust-bitcoin-hashes-0.14.100
  (crate-source "bitcoin_hashes" "0.14.100"
                "0gwfj642yka9zwxqkjji4ilg8i8zb7i164gbdv41yfhkdsjh368c"))

(define rust-bitcoin-internals-0.3.0
  (crate-source "bitcoin-internals" "0.3.0"
                "1lmyljcxy1466ljq2ksj97igprcry2hjkigzzrn6xc07m8abxg9h"))

(define rust-bitcoin-internals-0.5.0
  (crate-source "bitcoin-internals" "0.5.0"
                "0r7sbi43wmg9w6rkby2lyb76bhaxciimrd77dghyip8jy78j42m3"))

(define rust-bitcoin-io-0.1.100
  (crate-source "bitcoin-io" "0.1.100"
                "0xg1i60v4cb9z6w4jp293q1p38w8vlzl05hrpfkxw8kgn3q1sc0i"))

(define rust-bitcoin-io-0.1.3
  (crate-source "bitcoin-io" "0.1.3"
                "1bvbhm5yqv3kqrwm5d79yjak1djjkgnkamcc373v1vckgamw8iqb"))

(define rust-bitcoin-slices-0.10.0
  (crate-source "bitcoin_slices" "0.10.0"
                "1ys263kvrb14nrwxsac3jyxrfgi1llwvblhk5bz5mj6zgwjx8hvr"))

(define rust-bitcoin-test-data-0.2.0
  (crate-source "bitcoin-test-data" "0.2.0"
                "0d1zc08fxl79adginhkysg54nlddfybw9adzw5nbrqywz5a8c60c"))

(define rust-bitcoin-units-0.1.100
  (crate-source "bitcoin-units" "0.1.100"
                "0idqyd82nrc0qzr3fsl62i6zq4b2arda7dnbqhi1n3cdnxbx3fjp"))

(define rust-bitcoin-units-0.1.2
  (crate-source "bitcoin-units" "0.1.2"
                "1qk303kiz3qyyn4dc4bff5wr2q7j0g1k0gbyyc3nv1r5mayci1aj"))

(define rust-bitcoincore-rpc-0.19.0
  (crate-source "bitcoincore-rpc" "0.19.0"
                "1vl09sfqrni4blwpkff6in0k56plqqk63hxv9gxsy8fk1yp27pdf"))

(define rust-bitcoincore-rpc-json-0.19.0
  (crate-source "bitcoincore-rpc-json" "0.19.0"
                "06p7y0cps9b3k5rvgiixk5acjld6j9akxxqfx048bfgsqn1rb46q"))

(define rust-bitflags-2.9.1
  (crate-source "bitflags" "2.9.1"
                "0rz9rpp5wywwqb3mxfkywh4drmzci2fch780q7lifbf6bsc5d3hv"))

(define rust-block-buffer-0.10.4
  (crate-source "block-buffer" "0.10.4"
                "0w9sa2ypmrsqqvc20nhwr75wbb5cjr4kkyhpjm1z1lv2kdicfy1h"))

(define rust-block2-0.6.2
  (crate-source "block2" "0.6.2"
                "1xcfllzx6c3jc554nmb5qy6xmlkl6l6j5ib4wd11800n0n3rvsyd"))

(define rust-bzip2-sys-0.1.13+1.0.8
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "bzip2-sys" "0.1.13+1.0.8"
                "056c39pgjh4272bdslv445f5ry64xvb0f7nph3z7860ln8rzynr2"))

(define rust-cargo-toml-0.14.1
  (crate-source "cargo_toml" "0.14.1"
                "1hmc4bzr1hkaanss0wr7yiv4p7g8nybndw6mrpi42h2929iw7yrb"))

(define rust-cc-1.2.23
  (crate-source "cc" "1.2.23"
                "0ripmr35ix8lhszbkmr8pg8y61d4lv9xgfcs8jry5havkrmchjjz"))

(define rust-cc-1.2.64
  (crate-source "cc" "1.2.64"
                "07shcd8faxw7csz13m3cg2mj6i8z07pqs960k181pscbjpyqgn6s"))

(define rust-cexpr-0.6.0
  (crate-source "cexpr" "0.6.0"
                "0rl77bwhs5p979ih4r0202cn5jrfsrbgrksp40lkfz5vk1x3ib3g"))

(define rust-cfg-aliases-0.2.1
  (crate-source "cfg_aliases" "0.2.1"
                "092pxdc1dbgjb6qvh83gk56rkic2n2ybm4yvy76cgynmzi3zwfk1"))

(define rust-cfg-if-1.0.0
  (crate-source "cfg-if" "1.0.0"
                "1za0vb97n4brpzpv8lsbnzmq5r8f2b0cpqqr0sy8h5bn751xxwds"))

(define rust-cfg-if-1.0.4
  (crate-source "cfg-if" "1.0.4"
                "008q28ajc546z5p2hcwdnckmg0hia7rnx52fni04bwqkzyrghc4k"))

(define rust-chunked-transfer-1.5.0
  (crate-source "chunked_transfer" "1.5.0"
                "00a9h3csr1xwkqrzpz5kag4h92zdkrnxq4ppxidrhrx29syf6kbf"))

(define rust-clang-sys-1.8.1
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "clang-sys" "1.8.1"
                "1x1r9yqss76z8xwpdanw313ss6fniwc1r7dzb5ycjn0ph53kj0hb"))

(define rust-configure-me-0.4.0
  (crate-source "configure_me" "0.4.0"
                "17dk22avjdw9gz4fikfqflygnbnldkqxvs7yv9dqa9nrxayiyg6h"))

(define rust-configure-me-codegen-0.4.8
  (crate-source "configure_me_codegen" "0.4.8"
                "1shians5yf5a2agnsdk7wljdj2zvh6f2305bx2q1jyk6fl188mjy"))

(define rust-cpufeatures-0.2.17
  (crate-source "cpufeatures" "0.2.17"
                "10023dnnaghhdl70xcds12fsx2b966sxbxjq5sxs49mvxqw5ivar"))

(define rust-crossbeam-channel-0.5.15
  (crate-source "crossbeam-channel" "0.5.15"
                "1cicd9ins0fkpfgvz9vhz3m9rpkh6n8d3437c3wnfsdkd3wgif42"))

(define rust-crossbeam-deque-0.8.6
  (crate-source "crossbeam-deque" "0.8.6"
                "0l9f1saqp1gn5qy0rxvkmz4m6n7fc0b3dbm6q1r5pmgpnyvi3lcx"))

(define rust-crossbeam-epoch-0.9.18
  (crate-source "crossbeam-epoch" "0.9.18"
                "03j2np8llwf376m3fxqx859mgp9f83hj1w34153c7a9c7i5ar0jv"))

(define rust-crossbeam-utils-0.8.21
  (crate-source "crossbeam-utils" "0.8.21"
                "0a3aa2bmc8q35fb67432w16wvi54sfmb69rk9h5bhd18vw0c99fh"))

(define rust-crypto-common-0.1.6
  (crate-source "crypto-common" "0.1.6"
                "1cvby95a6xg7kxdz5ln3rl9xh66nz66w46mm3g56ri1z5x815yqv"))

(define rust-ctrlc-3.5.1
  (crate-source "ctrlc" "3.5.1"
                "146p40m5mj6w4nncj3wpsh0dlm0r0rjyblifp8sk1xxgqj4nlwvk"))

(define rust-digest-0.10.7
  (crate-source "digest" "0.10.7"
                "14p2n6ih29x81akj097lvz7wi9b6b9hvls0lwrv7b6xwyy0s5ncy"))

(define rust-dirs-next-2.0.0
  (crate-source "dirs-next" "2.0.0"
                "1q9kr151h9681wwp6is18750ssghz6j9j7qm7qi1ngcwy7mzi35r"))

(define rust-dirs-sys-next-0.1.2
  (crate-source "dirs-sys-next" "0.1.2"
                "0kavhavdxv4phzj4l0psvh55hszwnr0rcz8sxbvx20pyqi2a3gaf"))

(define rust-dispatch2-0.3.0
  (crate-source "dispatch2" "0.3.0"
                "1v1ak9w0s8z1g13x4mj2y5im9wmck0i2vf8f8wc9l1n6lqi9z849"))

(define rust-either-1.15.0
  (crate-source "either" "1.15.0"
                "069p1fknsmzn9llaizh77kip0pqmcwpdsykv2x30xpjyija5gis8"))

(define rust-env-logger-0.10.2
  (crate-source "env_logger" "0.10.2"
                "1005v71kay9kbz1d5907l0y7vh9qn2fqsp2yfgb8bjvin6m0bm2c"))

(define rust-errno-0.3.12
  (crate-source "errno" "0.3.12"
                "066ss2qln9z5q4816d3wcvq2bzasn7dajfkhcfqflfsy6pwlx8ff"))

(define rust-fastrand-2.3.0
  (crate-source "fastrand" "2.3.0"
                "1ghiahsw1jd68df895cy5h3gzwk30hndidn3b682zmshpgmrx41p"))

(define rust-find-msvc-tools-0.1.9
  (crate-source "find-msvc-tools" "0.1.9"
                "10nmi0qdskq6l7zwxw5g56xny7hb624iki1c39d907qmfh3vrbjv"))

(define rust-fmt2io-1.0.0
  (crate-source "fmt2io" "1.0.0"
                "1j323pq7sbv7q3f0axr9bsa0wc147yk868f2dhlybxx99ll2jqbb"))

(define rust-fnv-1.0.7
  (crate-source "fnv" "1.0.7"
                "1hc2mcqha06aibcaza94vbi81j6pr9a1bbxrxjfhc91zin8yr7iz"))

(define rust-generic-array-0.14.7
  (crate-source "generic-array" "0.14.7"
                "16lyyrzrljfq424c3n8kfwkqihlimmsg5nhshbbp48np3yjrqr45"))

(define rust-getrandom-0.2.16
  (crate-source "getrandom" "0.2.16"
                "14l5aaia20cc6cc08xdlhrzmfcylmrnprwnna20lqf746pqzjprk"))

(define rust-getrandom-0.2.17
  (crate-source "getrandom" "0.2.17"
                "1l2ac6jfj9xhpjjgmcx6s1x89bbnw9x6j9258yy6xjkzpq0bqapz"))

(define rust-getrandom-0.3.3
  (crate-source "getrandom" "0.3.3"
                "1x6jl875zp6b2b6qp9ghc84b0l76bvng2lvm8zfcmwjl7rb5w516"))

(define rust-getrandom-0.3.4
  (crate-source "getrandom" "0.3.4"
                "1zbpvpicry9lrbjmkd4msgj3ihff1q92i334chk7pzf46xffz7c9"))

(define rust-glob-0.3.2
  (crate-source "glob" "0.3.2"
                "1cm2w34b5w45fxr522h5b0fv1bxchfswcj560m3pnjbia7asvld8"))

(define rust-hashbrown-0.14.5
  (crate-source "hashbrown" "0.14.5"
                "1wa1vy1xs3mp11bn3z9dv0jricgr6a2j0zkf1g19yz3vw4il89z5"))

(define rust-hermit-abi-0.5.1
  (crate-source "hermit-abi" "0.5.1"
                "026bh0y8gpfd62gjm7gx6nyf6bgdyxdn0jc67i1ysl37hm3cwm7i"))

(define rust-hex-0.4.3
  (crate-source "hex" "0.4.3"
                "0w1a4davm1lgzpamwnba907aysmlrnygbqmfis2mqjx5m552a93z"))

(define rust-hex-conservative-0.2.2
  (crate-source "hex-conservative" "0.2.2"
                "17qba5mg59b15gld8jz7xywzi6vj8ycipr041k26fqk0mhc6v87x"))

(define rust-hex-conservative-1.2.0
  (crate-source "hex-conservative" "1.2.0"
                "041a52y2pj6nwl12xniihprdbxgiyn564m42qpzz7k31yf2i2hrm"))

(define rust-hex-lit-0.1.1
  (crate-source "hex_lit" "0.1.1"
                "1g8bln2js2c49ray6fy6c9bk9wfm5hnwjspx7jqng60m7whx249h"))

(define rust-httpdate-1.0.3
  (crate-source "httpdate" "1.0.3"
                "1aa9rd2sac0zhjqh24c9xvir96g188zldkx0hr6dnnlx5904cfyz"))

(define rust-humantime-2.2.0
  (crate-source "humantime" "2.2.0"
                "17rz8jhh1mcv4b03wnknhv1shwq2v9vhkhlfg884pprsig62l4cv"))

(define rust-is-terminal-0.4.16
  (crate-source "is-terminal" "0.4.16"
                "1acm63whnpwiw1padm9bpqz04sz8msymrmyxc55mvlq8hqqpykg0"))

(define rust-itertools-0.12.1
  (crate-source "itertools" "0.12.1"
                "0s95jbb3ndj1lvfxyq5wanc0fm0r6hg6q4ngb92qlfdxvci10ads"))

(define rust-itoa-1.0.15
  (crate-source "itoa" "1.0.15"
                "0b4fj9kz54dr3wam0vprjwgygvycyw8r0qwg7vp19ly8b2w16psa"))

(define rust-itoa-1.0.18
  (crate-source "itoa" "1.0.18"
                "10jnd1vpfkb8kj38rlkn2a6k02afvj3qmw054dfpzagrpl6achlg"))

(define rust-jobserver-0.1.33
  (crate-source "jobserver" "0.1.33"
                "12jkn3cxvfs7jsb6knmh9y2b41lwmrk3vdqywkmssx61jzq65wiq"))

(define rust-jsonrpc-0.18.0
  (crate-source "jsonrpc" "0.18.0"
                "1gz12rk9zvw9ab07pzak08yacnps1i103brwnznfyxqx6j6s6qin"))

(define rust-lazy-static-1.5.0
  (crate-source "lazy_static" "1.5.0"
                "1zk6dqqni0193xg6iijh7i3i44sryglwgvx20spdvwk3r6sbrlmv"))

(define rust-lazycell-1.3.0
  (crate-source "lazycell" "1.3.0"
                "0m8gw7dn30i0zjjpjdyf6pc16c34nl71lpv461mix50x3p70h3c3"))

(define rust-libc-0.2.178
  (crate-source "libc" "0.2.178"
                "1490yks6mria93i3xdva1gm05cjz824g14mbv0ph32lxma6kvj9p"))

(define rust-libc-0.2.186
  (crate-source "libc" "0.2.186"
                "0rnyhzjyqq9x56skkllbjzzzwym3r61lq3l4hqj64v71gw0r3av8"))

(define rust-libredox-0.1.3
  (crate-source "libredox" "0.1.3"
                "139602gzgs0k91zb7dvgj1qh4ynb8g1lbxsswdim18hcb6ykgzy0"))

(define rust-libz-sys-1.1.22
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "libz-sys" "1.1.22"
                "07b5wxh0ska996kc0g2hanjhmb4di7ksm6ndljhr4pi0vykyfw4b"))

(define rust-linux-raw-sys-0.11.0
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "linux-raw-sys" "0.11.0"
                "0fghx0nn8nvbz5yzgizfcwd6ap2pislp68j8c1bwyr6sacxkq7fz"))

(define rust-linux-raw-sys-0.4.15
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "linux-raw-sys" "0.4.15"
                "1aq7r2g7786hyxhv40spzf2nhag5xbw2axxc1k8z5k1dsgdm4v6j"))

(define rust-lock-api-0.4.12
  (crate-source "lock_api" "0.4.12"
                "05qvxa6g27yyva25a5ghsg85apdxkvr77yhkyhapj6r8vnf8pbq7"))

(define rust-log-0.4.29
  (crate-source "log" "0.4.29"
                "15q8j9c8g5zpkcw0hnd6cf2z7fxqnvsjh3rw5mv5q10r83i34l2y"))

(define rust-memchr-2.7.4
  (crate-source "memchr" "2.7.4"
                "18z32bhxrax0fnjikv475z7ii718hq457qwmaryixfxsl2qrmjkq"))

(define rust-memchr-2.8.2
  (crate-source "memchr" "2.8.2"
                "1i33wr49pcz2sbd12nds3n9fszay8kq5bk78gwciz462mcs49448"))

(define rust-minimal-lexical-0.2.1
  (crate-source "minimal-lexical" "0.2.1"
                "16ppc5g84aijpri4jzv14rvcnslvlpphbszc7zzp6vfkddf4qdb8"))

(define rust-miniscript-12.3.7
  (crate-source "miniscript" "12.3.7"
                "1kx4nnghwbpnvmpw57ilwsvzlz818zppm7znvfdvs20lxz0kqd5q"))

(define rust-minreq-2.13.4
  (crate-source "minreq" "2.13.4"
                "1sawrpb0q93631mhq6hx7c6czz5b1wc8i598q5pb8dvq8yxamlph"))

(define rust-nix-0.30.1
  (crate-source "nix" "0.30.1"
                "1dixahq9hk191g0c2ydc0h1ppxj0xw536y6rl63vlnp06lx3ylkl"))

(define rust-nom-7.1.3
  (crate-source "nom" "7.1.3"
                "0jha9901wxam390jcf5pfa0qqfrgh8li787jx2ip0yk5b8y9hwyj"))

(define rust-objc2-0.6.3
  (crate-source "objc2" "0.6.3"
                "01ccrb558qav2rqrmk0clzqzdd6r1rmicqnf55xqam7cw2f5khmp"))

(define rust-objc2-encode-4.1.0
  (crate-source "objc2-encode" "4.1.0"
                "0cqckp4cpf68mxyc2zgnazj8klv0z395nsgbafa61cjgsyyan9gg"))

(define rust-once-cell-1.21.3
  (crate-source "once_cell" "1.21.3"
                "0b9x77lb9f1j6nqgf5aka4s2qj0nly176bpbrv6f9iakk5ff3xa2"))

(define rust-once-cell-1.21.4
  (crate-source "once_cell" "1.21.4"
                "0l1v676wf71kjg2khch4dphwh1jp3291ffiymr2mvy1kxd5kwz4z"))

(define rust-parking-lot-0.12.3
  (crate-source "parking_lot" "0.12.3"
                "09ws9g6245iiq8z975h8ycf818a66q3c6zv4b5h8skpm7hc1igzi"))

(define rust-parking-lot-core-0.9.10
  (crate-source "parking_lot_core" "0.9.10"
                "1y3cf9ld9ijf7i4igwzffcn0xl16dxyn4c5bwgjck1dkgabiyh0y"))

(define rust-parse-arg-0.1.6
  (crate-source "parse_arg" "0.1.6"
                "09g29xs7rkrfci80nsnb5al8fycrwda1jl8c9vn6y0xnr365pw1j"))

(define rust-parse-arg-1.0.1
  (crate-source "parse_arg" "1.0.1"
                "196kwixf3pldds43mg2vk236y8y2qf9afvg5wbqyly8bd0zw7pav"))

(define rust-pkg-config-0.3.32
  (crate-source "pkg-config" "0.3.32"
                "0k4h3gnzs94sjb2ix6jyksacs52cf1fanpwsmlhjnwrdnp8dppby"))

(define rust-ppv-lite86-0.2.21
  (crate-source "ppv-lite86" "0.2.21"
                "1abxx6qz5qnd43br1dd9b2savpihzjza8gb4fbzdql1gxp2f7sl5"))

(define rust-proc-macro2-1.0.106
  (crate-source "proc-macro2" "1.0.106"
                "0d09nczyaj67x4ihqr5p7gxbkz38gxhk4asc0k8q23g9n85hzl4g"))

(define rust-proc-macro2-1.0.95
  (crate-source "proc-macro2" "1.0.95"
                "0y7pwxv6sh4fgg6s715ygk1i7g3w02c0ljgcsfm046isibkfbcq2"))

(define rust-procfs-0.17.0
  (crate-source "procfs" "0.17.0"
                "17swyjqinpb745f07dpdi7c8q37hxvhx9xmmsi2dhxaj2kc74nyc"))

(define rust-procfs-core-0.17.0
  (crate-source "procfs-core" "0.17.0"
                "1v0jdbyc1rq1x22m0wn7n4iq4h86gdls38wqfg06zc29hcnz1793"))

(define rust-prometheus-0.14.0
  (crate-source "prometheus" "0.14.0"
                "0fpl98whrg5j4bpb3qfswii4yfa58zws7rl7rnd0m58bimnk599w"))

(define rust-protobuf-3.7.2
  (crate-source "protobuf" "3.7.2"
                "1x4riz4znnjsqpdxnhxj0aq8rfivmbv4hfqmd3gbbn77v96isnnn"))

(define rust-protobuf-support-3.7.2
  (crate-source "protobuf-support" "3.7.2"
                "1mnpn2q96bxm2vidh86m5p2x5z0z8rgfyixk1wlgjiqa3vrw4diy"))

(define rust-quote-1.0.40
  (crate-source "quote" "1.0.40"
                "1394cxjg6nwld82pzp2d4fp6pmaz32gai1zh9z5hvh0dawww118q"))

(define rust-quote-1.0.45
  (crate-source "quote" "1.0.45"
                "095rb5rg7pbnwdp6v8w5jw93wndwyijgci1b5lw8j1h5cscn3wj1"))

(define rust-r-efi-5.2.0
  (crate-source "r-efi" "5.2.0"
                "1ig93jvpqyi87nc5kb6dri49p56q7r7qxrn8kfizmqkfj5nmyxkl"))

(define rust-r-efi-5.3.0
  (crate-source "r-efi" "5.3.0"
                "03sbfm3g7myvzyylff6qaxk4z6fy76yv860yy66jiswc2m6b7kb9"))

(define rust-rand-0.8.5
  (crate-source "rand" "0.8.5"
                "013l6931nn7gkc23jz5mm3qdhf93jjf0fg64nz2lp4i51qd8vbrl"))

(define rust-rand-0.8.6
  (crate-source "rand" "0.8.6"
                "12kd4rljn86m00rcaz4c1rcya4mb4gk5ig6i8xq00a8wjgxfr82w"))

(define rust-rand-0.9.4
  (crate-source "rand" "0.9.4"
                "1sknbxgs6nfg0nxdd7689lwbyr2i4vaswchrv4b34z8vpc3azia4"))

(define rust-rand-chacha-0.3.1
  (crate-source "rand_chacha" "0.3.1"
                "123x2adin558xbhvqb8w4f6syjsdkmqff8cxwhmjacpsl1ihmhg6"))

(define rust-rand-chacha-0.9.0
  (crate-source "rand_chacha" "0.9.0"
                "1jr5ygix7r60pz0s1cv3ms1f6pd1i9pcdmnxzzhjc3zn3mgjn0nk"))

(define rust-rand-core-0.6.4
  (crate-source "rand_core" "0.6.4"
                "0b4j2v4cb5krak1pv6kakv4sz6xcwbrmy2zckc32hsigbrwy82zc"))

(define rust-rand-core-0.9.5
  (crate-source "rand_core" "0.9.5"
                "0g6qc5r3f0hdmz9b11nripyp9qqrzb0xqk9piip8w8qlvqkcibvn"))

(define rust-rayon-1.11.0
  (crate-source "rayon" "1.11.0"
                "13x5fxb7rn4j2yw0cr26n7782jkc7rjzmdkg42qxk3xz0p8033rn"))

(define rust-rayon-core-1.13.0
  (crate-source "rayon-core" "1.13.0"
                "14dbr0sq83a6lf1rfjq5xdpk5r6zgzvmzs5j6110vlv2007qpq92"))

(define rust-redox-syscall-0.5.12
  (crate-source "redox_syscall" "0.5.12"
                "1by5k76jr4kjy37287ifn56dzw6jh6nrwnrjm29j615ayafcm3wj"))

(define rust-redox-users-0.4.6
  (crate-source "redox_users" "0.4.6"
                "0hya2cxx6hxmjfxzv9n8rjl5igpychav7zfi1f81pz6i4krry05s"))

(define rust-regex-1.11.1
  (crate-source "regex" "1.11.1"
                "148i41mzbx8bmq32hsj1q4karkzzx5m60qza6gdw4pdc9qdyyi5m"))

(define rust-regex-automata-0.4.9
  (crate-source "regex-automata" "0.4.9"
                "02092l8zfh3vkmk47yjc8d631zhhcd49ck2zr133prvd3z38v7l0"))

(define rust-regex-syntax-0.8.5
  (crate-source "regex-syntax" "0.8.5"
                "0p41p3hj9ww7blnbwbj9h7rwxzxg0c1hvrdycgys8rxyhqqw859b"))

(define rust-rust-librocksdb-sys-0.32.0+9.10.0
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "rust-librocksdb-sys" "0.32.0+9.10.0"
                "1l4cvrgavbl8y54nkwisyzsslfkq2l2vy0mrvkljd2fnmmznn52h"))

(define rust-rust-rocksdb-0.36.0
  (crate-source "rust-rocksdb" "0.36.0"
                "0bscga4x79kcl65b5yd256bc0cm7gh20dgkxkxlssgxa2jkqiw1v"))

(define rust-rustc-hash-1.1.0
  (crate-source "rustc-hash" "1.1.0"
                "1qkc5khrmv5pqi5l5ca9p5nl5hs742cagrndhbrlk3dhlrx3zm08"))

(define rust-rustix-0.38.44
  (crate-source "rustix" "0.38.44"
                "0m61v0h15lf5rrnbjhcb9306bgqrhskrqv7i1n0939dsw8dbrdgx"))

(define rust-rustix-1.1.3
  (crate-source "rustix" "1.1.3"
                "0d0z2zcw4rwzni1hm8snw8xdxwwrij336m31c4ghq66cghj9wv0l"))

(define rust-scopeguard-1.2.0
  (crate-source "scopeguard" "1.2.0"
                "0jcz9sd47zlsgcnm1hdw0664krxwb5gczlif4qngj2aif8vky54l"))

(define rust-secp256k1-0.29.1
  (crate-source "secp256k1" "0.29.1"
                "04w122fb3mnyphkrl3z64asqq9j6qjygrzzh4hbnwmnlr5dk2rcl"))

(define rust-secp256k1-sys-0.10.1
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "secp256k1-sys" "0.10.1"
                "1n81a1qhwxncvkv38bw36xwfjlipkb31f2jk435shfix6f17hf6l"))

(define rust-secp256k1-sys-0.11.0
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "secp256k1-sys" "0.11.0"
                "0f7viv4mlpsbjajxvkrw03mndpjpx2q2sb3hv3qdmyjqf5q17ffw"))

(define rust-serde-1.0.223
  (crate-source "serde" "1.0.223"
                "1b3vgbq3m9p6y1xzf776cjgkg4vhlpnvap6sjgi8ipmdc0cxf1d5"))

(define rust-serde-1.0.228
  (crate-source "serde" "1.0.228"
                "17mf4hhjxv5m90g42wmlbc61hdhlm6j9hwfkpcnd72rpgzm993ls"))

(define rust-serde-core-1.0.223
  (crate-source "serde_core" "1.0.223"
                "1sdrkcqf3nd5r8qb8wk7vd6iv3rjxas90jn879xslrkn6nyprx90"))

(define rust-serde-core-1.0.228
  (crate-source "serde_core" "1.0.228"
                "1bb7id2xwx8izq50098s5j2sqrrvk31jbbrjqygyan6ask3qbls1"))

(define rust-serde-derive-1.0.223
  (crate-source "serde_derive" "1.0.223"
                "0mhsl2l92ghpam8mpkkbbnx6b8g5jqcykhcyd5p30zpiz83qshix"))

(define rust-serde-derive-1.0.228
  (crate-source "serde_derive" "1.0.228"
                "0y8xm7fvmr2kjcd029g9fijpndh8csv5m20g4bd76w8qschg4h6m"))

(define rust-serde-json-1.0.149
  (crate-source "serde_json" "1.0.149"
                "11jdx4vilzrjjd1dpgy67x5lgzr0laplz30dhv75lnf5ffa07z43"))

(define rust-serde-json-1.0.150
  (crate-source "serde_json" "1.0.150"
                "1ffgfhy9kndjnrz8lmy95pr758p2zk8dxv6yi99x0vkkni24w0g8"))

(define rust-sha2-0.10.9
  (crate-source "sha2" "0.10.9"
                "10xjj843v31ghsksd9sl9y12qfc48157j1xpb8v1ml39jy0psl57"))

(define rust-shlex-1.3.0
  (crate-source "shlex" "1.3.0"
                "0r1y6bv26c1scpxvhg2cabimrmwgbp4p3wy6syj9n0c4s3q2znhg"))

(define rust-shlex-2.0.1
  (crate-source "shlex" "2.0.1"
                "1fjsll1cd7d2bcpdij9kd6w62rpbc7qqzvydvs021vsmr1cxvypq"))

(define rust-signal-hook-0.4.3
  (crate-source "signal-hook" "0.4.3"
                "13pv6n4sacdh8dr8i9s5gi0ahp62xqk9bkkxlbsgk7sglyfp0mrv"))

(define rust-signal-hook-registry-1.4.5
  (crate-source "signal-hook-registry" "1.4.5"
                "042lkqrpnlrgvrrcirgigxyp1zk70d8v0fsr5w7a18k3bw2vh0wj"))

(define rust-smallvec-1.15.0
  (crate-source "smallvec" "1.15.0"
                "1sgfw8z729nlxk8k13dhs0a762wnaxmlx70a7xlf3wz989bjh5w9"))

(define rust-syn-2.0.101
  (crate-source "syn" "2.0.101"
                "1brwsh7fn3bnbj50d2lpwy9akimzb3lghz0ai89j8fhvjkybgqlc"))

(define rust-syn-2.0.117
  (crate-source "syn" "2.0.117"
                "16cv7c0wbn8amxc54n4w15kxlx5ypdmla8s0gxr2l7bv7s0bhrg6"))

(define rust-tempfile-3.24.0
  (crate-source "tempfile" "3.24.0"
                "171fz3h6rj676miq15fyv1hnv69p426mlp8489bwa1b3xg3sjpb5"))

(define rust-termcolor-1.4.1
  (crate-source "termcolor" "1.4.1"
                "0mappjh3fj3p2nmrg4y7qv94rchwi9mzmgmfflr8p2awdj7lyy86"))

(define rust-thiserror-1.0.69
  (crate-source "thiserror" "1.0.69"
                "0lizjay08agcr5hs9yfzzj6axs53a2rgx070a1dsi3jpkcrzbamn"))

(define rust-thiserror-2.0.16
  (crate-source "thiserror" "2.0.16"
                "1h30bqyjn5s9ypm668yd9849371rzwk185klwgjg503k2hadcrrl"))

(define rust-thiserror-impl-1.0.69
  (crate-source "thiserror-impl" "1.0.69"
                "1h84fmn2nai41cxbhk6pqf46bxqq1b344v8yz089w1chzi76rvjg"))

(define rust-thiserror-impl-2.0.16
  (crate-source "thiserror-impl" "2.0.16"
                "0q3r1ipr1rhff6cgrcvc0njffw17rpcqz9hdc7p754cbqkhinpkc"))

(define rust-tiny-http-0.12.0
  (crate-source "tiny_http" "0.12.0"
                "10nw9kk2i2aq4l4csy0825qkq0l66f9mz2c1n57yg8hkckgib69q"))

(define rust-toml-0.5.11
  (crate-source "toml" "0.5.11"
                "0d2266nx8b3n22c7k24x4428z6di8n83a9n466jm7a2hipfz1xzl"))

(define rust-typenum-1.18.0
  (crate-source "typenum" "1.18.0"
                "0gwgz8n91pv40gabrr1lzji0b0hsmg0817njpy397bq7rvizzk0x"))

(define rust-unicode-ident-1.0.18
  (crate-source "unicode-ident" "1.0.18"
                "04k5r6sijkafzljykdq26mhjpmhdx4jwzvn1lh90g9ax9903jpss"))

(define rust-unicode-ident-1.0.24
  (crate-source "unicode-ident" "1.0.24"
                "0xfs8y1g7syl2iykji8zk5hgfi5jw819f5zsrbaxmlzwsly33r76"))

(define rust-unicode-segmentation-1.12.0
  (crate-source "unicode-segmentation" "1.12.0"
                "14qla2jfx74yyb9ds3d2mpwpa4l4lzb9z57c6d2ba511458z5k7n"))

(define rust-vcpkg-0.2.15
  (crate-source "vcpkg" "0.2.15"
                "09i4nf5y8lig6xgj3f7fyrvzd3nlaw4znrihw8psidvv5yk4xkdc"))

(define rust-version-check-0.9.5
  (crate-source "version_check" "0.9.5"
                "0nhhi4i5x89gm911azqbn7avs9mdacw2i3vcz3cnmz3mv4rqz4hb"))

(define rust-void-1.0.2
  (crate-source "void" "1.0.2"
                "0zc8f0ksxvmhvgx4fdg0zyn6vdnbxd2xv9hfx4nhzg6kbs4f80ka"))

(define rust-wasi-0.11.0+wasi-snapshot-preview1
  (crate-source "wasi" "0.11.0+wasi-snapshot-preview1"
                "08z4hxwkpdpalxjps1ai9y7ihin26y9f476i53dv98v45gkqg3cw"))

(define rust-wasi-0.11.1+wasi-snapshot-preview1
  (crate-source "wasi" "0.11.1+wasi-snapshot-preview1"
                "0jx49r7nbkbhyfrfyhz0bm4817yrnxgd3jiwwwfv0zl439jyrwyc"))

(define rust-wasi-0.14.2+wasi-0.2.4
  (crate-source "wasi" "0.14.2+wasi-0.2.4"
                "1cwcqjr3dgdq8j325awgk8a715h0hg0f7jqzsb077n4qm6jzk0wn"))

(define rust-wasip2-1.0.3+wasi-0.2.9
  (crate-source "wasip2" "1.0.3+wasi-0.2.9"
                "1mi3w855dz99xzjqc4aa8c9q5b6z1y5c963pkk4cvmr6vdr4c1i0"))

(define rust-winapi-0.3.9
  (crate-source "winapi" "0.3.9"
                "06gl025x418lchw1wxj64ycr7gha83m44cjr5sarhynd9xkrm0sw"))

(define rust-winapi-i686-pc-windows-gnu-0.4.0
  (crate-source "winapi-i686-pc-windows-gnu" "0.4.0"
                "1dmpa6mvcvzz16zg6d5vrfy4bxgg541wxrcip7cnshi06v38ffxc"))

(define rust-winapi-util-0.1.9
  (crate-source "winapi-util" "0.1.9"
                "1fqhkcl9scd230cnfj8apfficpf5c9vhwnk4yy9xfc1sw69iq8ng"))

(define rust-winapi-x86-64-pc-windows-gnu-0.4.0
  (crate-source "winapi-x86_64-pc-windows-gnu" "0.4.0"
                "0gqq64czqb64kskjryj8isp62m2sgvx25yyj3kpc2myh85w24bki"))

(define rust-windows-aarch64-gnullvm-0.52.6
  (crate-source "windows_aarch64_gnullvm" "0.52.6"
                "1lrcq38cr2arvmz19v32qaggvj8bh1640mdm9c2fr877h0hn591j"))

(define rust-windows-aarch64-msvc-0.52.6
  (crate-source "windows_aarch64_msvc" "0.52.6"
                "0sfl0nysnz32yyfh773hpi49b1q700ah6y7sacmjbqjjn5xjmv09"))

(define rust-windows-i686-gnu-0.52.6
  (crate-source "windows_i686_gnu" "0.52.6"
                "02zspglbykh1jh9pi7gn8g1f97jh1rrccni9ivmrfbl0mgamm6wf"))

(define rust-windows-i686-gnullvm-0.52.6
  (crate-source "windows_i686_gnullvm" "0.52.6"
                "0rpdx1537mw6slcpqa0rm3qixmsb79nbhqy5fsm3q2q9ik9m5vhf"))

(define rust-windows-i686-msvc-0.52.6
  (crate-source "windows_i686_msvc" "0.52.6"
                "0rkcqmp4zzmfvrrrx01260q3xkpzi6fzi2x2pgdcdry50ny4h294"))

(define rust-windows-link-0.2.0
  (crate-source "windows-link" "0.2.0"
                "0r9w2z96d5phmm185aq92z54jp9h2nqisa4wgc71idxbc436rr25"))

(define rust-windows-sys-0.59.0
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "windows-sys" "0.59.0"
                "0fw5672ziw8b3zpmnbp9pdv1famk74f1l9fcbc3zsrzdg56vqf0y"))

(define rust-windows-sys-0.61.0
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "windows-sys" "0.61.0"
                "1ajpwsmzfcsa1r7i0dxzvfn24dp3525rcd7aq95ydvdj8171h0g2"))

(define rust-windows-targets-0.52.6
  (crate-source "windows-targets" "0.52.6"
                "0wwrx625nwlfp7k93r2rra568gad1mwd888h1jwnl0vfg5r4ywlv"))

(define rust-windows-x86-64-gnu-0.52.6
  (crate-source "windows_x86_64_gnu" "0.52.6"
                "0y0sifqcb56a56mvn7xjgs8g43p33mfqkd8wj1yhrgxzma05qyhl"))

(define rust-windows-x86-64-gnullvm-0.52.6
  (crate-source "windows_x86_64_gnullvm" "0.52.6"
                "03gda7zjx1qh8k9nnlgb7m3w3s1xkysg55hkd1wjch8pqhyv5m94"))

(define rust-windows-x86-64-msvc-0.52.6
  (crate-source "windows_x86_64_msvc" "0.52.6"
                "1v7rb5cibyzx8vak29pdrk8nx9hycsjs4w0jgms08qk49jl6v7sq"))

(define rust-wit-bindgen-0.57.1
  (crate-source "wit-bindgen" "0.57.1"
                "0vjk2jb593ri9k1aq4iqs2si9mrw5q46wxnn78im7hm7hx799gqy"))

(define rust-wit-bindgen-rt-0.39.0
  (crate-source "wit-bindgen-rt" "0.39.0"
                "1hd65pa5hp0nl664m94bg554h4zlhrzmkjsf6lsgsb7yc4734hkg"))

(define rust-zerocopy-0.8.25
  (crate-source "zerocopy" "0.8.25"
                "1jx07cd3b3456c9al9zjqqdzpf1abb0vf6z0fj8xnb93hfajsw51"))

(define rust-zerocopy-0.8.52
  (crate-source "zerocopy" "0.8.52"
                "0gv563swc1yn3k8w3wjj07a8q293rkx99nfp3a25vzzmbycj446f"))

(define rust-zerocopy-derive-0.8.25
  (crate-source "zerocopy-derive" "0.8.25"
                "1vsmpq0hp61xpqj9yk8b5jihkqkff05q1wv3l2568mhifl6y59i8"))

(define rust-zerocopy-derive-0.8.52
  (crate-source "zerocopy-derive" "0.8.52"
                "0c3rhsh4sd9kdym4z55zprybjkydy9y2gvw75d72aapcfa5z7rqs"))

(define rust-zmij-1.0.2
  (crate-source "zmij" "1.0.2"
                "0795wc0mal0ipxa4gass848bfgscgzhdpz04kwajvin5kn74wjhg"))

(define rust-zmij-1.0.21
  (crate-source "zmij" "1.0.21"
                "1amb5i6gz7yjb0dnmz5y669674pqmwbj44p4yfxfv2ncgvk8x15q"))

(define rust-zstd-sys-2.0.13+zstd.1.5.6
  ;; TODO REVIEW: Check bundled sources.
  (crate-source "zstd-sys" "2.0.13+zstd.1.5.6"
                "1almbackh06am0d2kc4a089n3al91jg3ahgg9kcrg3zfrwhhzzrq"))

(define-cargo-inputs lookup-cargo-inputs
  (electrs =>
   (list
    rust-aho-corasick-1.1.3
    rust-anyhow-1.0.98
    rust-arrayvec-0.7.6
    rust-ascii-1.1.0
    rust-autocfg-1.4.0
    rust-base58ck-0.1.0
    rust-base64-0.13.1
    rust-bech32-0.11.0
    rust-bindgen-0.69.5
    rust-bitcoin-0.32.8
    rust-bitcoin-internals-0.3.0
    rust-bitcoin-io-0.1.3
    rust-bitcoin-test-data-0.2.0
    rust-bitcoin-units-0.1.2
    rust-bitcoin-hashes-0.14.0
    rust-bitcoin-slices-0.10.0
    rust-bitcoincore-rpc-0.19.0
    rust-bitcoincore-rpc-json-0.19.0
    rust-bitflags-2.9.1
    rust-block-buffer-0.10.4
    rust-block2-0.6.2
    rust-bzip2-sys-0.1.13+1.0.8
    rust-cargo-toml-0.14.1
    rust-cc-1.2.23
    rust-cexpr-0.6.0
    rust-cfg-if-1.0.0
    rust-cfg-aliases-0.2.1
    rust-chunked-transfer-1.5.0
    rust-clang-sys-1.8.1
    rust-configure-me-0.4.0
    rust-configure-me-codegen-0.4.8
    rust-cpufeatures-0.2.17
    rust-crossbeam-channel-0.5.15
    rust-crossbeam-deque-0.8.6
    rust-crossbeam-epoch-0.9.18
    rust-crossbeam-utils-0.8.21
    rust-crypto-common-0.1.6
    rust-ctrlc-3.5.1
    rust-digest-0.10.7
    rust-dirs-next-2.0.0
    rust-dirs-sys-next-0.1.2
    rust-dispatch2-0.3.0
    rust-either-1.15.0
    rust-env-logger-0.10.2
    rust-errno-0.3.12
    rust-fastrand-2.3.0
    rust-fmt2io-1.0.0
    rust-fnv-1.0.7
    rust-generic-array-0.14.7
    rust-getrandom-0.2.16
    rust-getrandom-0.3.3
    rust-glob-0.3.2
    rust-hermit-abi-0.5.1
    rust-hex-0.4.3
    rust-hex-conservative-0.2.2
    rust-hex-lit-0.1.1
    rust-httpdate-1.0.3
    rust-humantime-2.2.0
    rust-is-terminal-0.4.16
    rust-itertools-0.12.1
    rust-itoa-1.0.15
    rust-jobserver-0.1.33
    rust-jsonrpc-0.18.0
    rust-lazy-static-1.5.0
    rust-lazycell-1.3.0
    rust-libc-0.2.178
    rust-libredox-0.1.3
    rust-libz-sys-1.1.22
    rust-linux-raw-sys-0.4.15
    rust-linux-raw-sys-0.11.0
    rust-lock-api-0.4.12
    rust-log-0.4.29
    rust-memchr-2.7.4
    rust-minimal-lexical-0.2.1
    rust-minreq-2.13.4
    rust-nix-0.30.1
    rust-nom-7.1.3
    rust-objc2-0.6.3
    rust-objc2-encode-4.1.0
    rust-once-cell-1.21.3
    rust-parking-lot-0.12.3
    rust-parking-lot-core-0.9.10
    rust-parse-arg-0.1.6
    rust-parse-arg-1.0.1
    rust-pkg-config-0.3.32
    rust-ppv-lite86-0.2.21
    rust-proc-macro2-1.0.95
    rust-procfs-0.17.0
    rust-procfs-core-0.17.0
    rust-prometheus-0.14.0
    rust-protobuf-3.7.2
    rust-protobuf-support-3.7.2
    rust-quote-1.0.40
    rust-r-efi-5.2.0
    rust-rand-0.8.5
    rust-rand-chacha-0.3.1
    rust-rand-core-0.6.4
    rust-rayon-1.11.0
    rust-rayon-core-1.13.0
    rust-redox-syscall-0.5.12
    rust-redox-users-0.4.6
    rust-regex-1.11.1
    rust-regex-automata-0.4.9
    rust-regex-syntax-0.8.5
    rust-rust-librocksdb-sys-0.32.0+9.10.0
    rust-rust-rocksdb-0.36.0
    rust-rustc-hash-1.1.0
    rust-rustix-0.38.44
    rust-rustix-1.1.3
    rust-scopeguard-1.2.0
    rust-secp256k1-0.29.1
    rust-secp256k1-sys-0.10.1
    rust-serde-1.0.223
    rust-serde-core-1.0.223
    rust-serde-derive-1.0.223
    rust-serde-json-1.0.149
    rust-sha2-0.10.9
    rust-shlex-1.3.0
    rust-signal-hook-0.4.3
    rust-signal-hook-registry-1.4.5
    rust-smallvec-1.15.0
    rust-syn-2.0.101
    rust-tempfile-3.24.0
    rust-termcolor-1.4.1
    rust-thiserror-1.0.69
    rust-thiserror-2.0.16
    rust-thiserror-impl-1.0.69
    rust-thiserror-impl-2.0.16
    rust-tiny-http-0.12.0
    rust-toml-0.5.11
    rust-typenum-1.18.0
    rust-unicode-ident-1.0.18
    rust-unicode-segmentation-1.12.0
    rust-vcpkg-0.2.15
    rust-version-check-0.9.5
    rust-void-1.0.2
    rust-wasi-0.11.0+wasi-snapshot-preview1
    rust-wasi-0.14.2+wasi-0.2.4
    rust-winapi-0.3.9
    rust-winapi-i686-pc-windows-gnu-0.4.0
    rust-winapi-util-0.1.9
    rust-winapi-x86-64-pc-windows-gnu-0.4.0
    rust-windows-link-0.2.0
    rust-windows-sys-0.59.0
    rust-windows-sys-0.61.0
    rust-windows-targets-0.52.6
    rust-windows-aarch64-gnullvm-0.52.6
    rust-windows-aarch64-msvc-0.52.6
    rust-windows-i686-gnu-0.52.6
    rust-windows-i686-gnullvm-0.52.6
    rust-windows-i686-msvc-0.52.6
    rust-windows-x86-64-gnu-0.52.6
    rust-windows-x86-64-gnullvm-0.52.6
    rust-windows-x86-64-msvc-0.52.6
    rust-wit-bindgen-rt-0.39.0
    rust-zerocopy-0.8.25
    rust-zerocopy-derive-0.8.25
    rust-zmij-1.0.2
    rust-zstd-sys-2.0.13+zstd.1.5.6
    ))
  (rust-bitcoin =>
   (list
    rust-arrayvec-0.7.6
    rust-base58ck-0.1.100
    rust-bech32-0.11.1
    rust-bitcoin-hashes-0.14.100
    rust-bitcoin-io-0.1.100
    rust-bitcoin-units-0.1.100
    rust-cc-1.2.64
    rust-find-msvc-tools-0.1.9
    rust-hex-conservative-0.2.2
    rust-hex-lit-0.1.1
    rust-secp256k1-0.29.1
    rust-secp256k1-sys-0.10.1
    rust-shlex-2.0.1
    ))
  (rust-bitcoin-hashes =>
   (list
    rust-arrayvec-0.7.6
    rust-bitcoin-consensus-encoding-1.0.0
    rust-bitcoin-internals-0.5.0
    rust-hex-conservative-1.2.0
    ))
  (rust-secp256k1 =>
   (list
    rust-arrayvec-0.7.6
    rust-bitcoin-hashes-0.14.100
    rust-bitcoin-io-0.1.100
    rust-cc-1.2.64
    rust-cfg-if-1.0.4
    rust-find-msvc-tools-0.1.9
    rust-getrandom-0.3.4
    rust-hex-conservative-0.2.2
    rust-libc-0.2.186
    rust-ppv-lite86-0.2.21
    rust-proc-macro2-1.0.106
    rust-quote-1.0.45
    rust-r-efi-5.3.0
    rust-rand-0.9.4
    rust-rand-chacha-0.9.0
    rust-rand-core-0.9.5
    rust-secp256k1-sys-0.11.0
    rust-shlex-2.0.1
    rust-syn-2.0.117
    rust-unicode-ident-1.0.24
    rust-wasip2-1.0.3+wasi-0.2.9
    rust-wit-bindgen-0.57.1
    rust-zerocopy-0.8.52
    rust-zerocopy-derive-0.8.52
    ))
  (rust-miniscript =>
   (list
    rust-arrayvec-0.7.6
    rust-base58ck-0.1.100
    rust-bech32-0.11.1
    rust-bitcoin-0.32.100
    rust-bitcoin-hashes-0.14.100
    rust-bitcoin-io-0.1.100
    rust-bitcoin-units-0.1.100
    rust-cc-1.2.64
    rust-find-msvc-tools-0.1.9
    rust-hex-conservative-0.2.2
    rust-hex-conservative-1.2.0
    rust-hex-lit-0.1.1
    rust-secp256k1-0.29.1
    rust-secp256k1-sys-0.10.1
    rust-shlex-2.0.1
    ))
  (rust-bdk-wallet =>
   (list
    rust-ahash-0.8.12
    rust-arrayvec-0.7.6
    rust-base58ck-0.1.100
    rust-base64-0.21.7
    rust-bdk-chain-0.23.3
    rust-bdk-core-0.6.3
    rust-bech32-0.11.1
    rust-bitcoin-0.32.100
    rust-bitcoin-hashes-0.14.100
    rust-bitcoin-io-0.1.100
    rust-bitcoin-units-0.1.100
    rust-cc-1.2.64
    rust-cfg-if-1.0.4
    rust-find-msvc-tools-0.1.9
    rust-getrandom-0.2.17
    rust-hashbrown-0.14.5
    rust-hex-conservative-0.2.2
    rust-hex-lit-0.1.1
    rust-itoa-1.0.18
    rust-libc-0.2.186
    rust-memchr-2.8.2
    rust-miniscript-12.3.7
    rust-once-cell-1.21.4
    rust-ppv-lite86-0.2.21
    rust-proc-macro2-1.0.106
    rust-quote-1.0.45
    rust-rand-0.8.6
    rust-rand-chacha-0.3.1
    rust-rand-core-0.6.4
    rust-secp256k1-0.29.1
    rust-secp256k1-sys-0.10.1
    rust-serde-1.0.228
    rust-serde-core-1.0.228
    rust-serde-derive-1.0.228
    rust-serde-json-1.0.150
    rust-shlex-2.0.1
    rust-syn-2.0.117
    rust-unicode-ident-1.0.24
    rust-version-check-0.9.5
    rust-wasi-0.11.1+wasi-snapshot-preview1
    rust-zerocopy-0.8.52
    rust-zerocopy-derive-0.8.52
    rust-zmij-1.0.21
    )))
